image: node:18
pages:
  stage: build
  tags:
    - docker
  cache:
    paths:
      - node_modules/
  script:
    - npm install -g pnpm
    - pnpm install
    - pnpm build
  artifacts:
    expire_in: 2 week
    paths:
      - public
  only:
    - master
