image: node:16
pages:
  stage: build
  tags:
    - shell
    - macos
  cache:
    paths:
      - node_modules/
  script:
    - pnpm install
    - pnpm build
  artifacts:
    expire_in: 2 week
    paths:
      - public
  only:
    - master
