name: 'weekly deploy'
on:
  schedule:
    # UTC + 8 -> Saturday 00:00, scheduler has delay
    - cron: '0 16 * * 5'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Fetch docs & Git push
        run: |
          npm run fetch:docs
          if [ -n "$(git status --porcelain)" ]; then
            today=`date +"%Y-%m-%d"`
            git config user.name "${{ github.actor }}"
            git config user.email "${{ github.actor }}@users.noreply.github.com"
            git remote set-url --add origin https://oauth2:${{ secrets.GITLAB_ACCESS_TOKEN }}@gitlab.com/bayi-95/my-blog.git
            git add .
            git commit -m "docs: update weekly docs on ${today} done"
            git push
          fi
